main: com.gmail.fingrambbg.generic.SpiroCraft
name: Spirograph
version: 1.15
api-version: 1.15
author: RoboEx
description: This bad boi gives you a template
commands:
   spiral:
     description: spiral
     usage: /spiral
     permission: spiral.spiral
     permission-message: You don't have permission